version: '3.5'

services: 
        web_dev:
          build: .
          command: python -u app.py
          ports:
                  - "8000:8000"
                  - "8003:8003"
                  - "8002:8002" 
          volumes:
                  - .:/source 

        mongodb:
                image: mongo:latest
                ports:
                        - 27017:27017
                volumes:
                  - .:/source 

        mongoseed:
                image: mongo:latest
                links: 
                  - mongodb 
                volumes:
                  - .:/source 
                entrypoint: ["mongorestore","--port=27017", "--gzip", "--db", "anhthudb", "/source/dump/anhthudb"]

networks:
        default:
                name: web_dev
