version: '3.5'

services:
  mongodb:
    build: .
    ports:
    - "27017:27017"
    volumes:
    - .:/source
    command: mongod

  mongoseed:
    image: mongo:4.0.4
    links:
    - mongodb
    volumes:
    - .:/source
    command: 
      "mongorestore --host mongodb --port 27017 --db anhthudb --gzip /source/dump/anhthudb"

networks:
    default:
        name: mongo
