SECRET_KEY = 'Dat Shiro'
DEBUG = True

MONGODB_DB = 'anhthudb'
MONGODB_HOST = '127.0.0.1'
DEFAULT_CONNECTION_NAME = 'anhthudb'

SESSION_KEY = 'sessionId'
DEBUG_TB_INTERCEPT_REDIRECTS = False

KUM = 'KEY_PUBLIC_MERCHANT'
KUPG = 'KEY_PUBLIC_PAYMENT_GATEWAY'

#EMAIL SETTINGS
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USE_TLS=False
MAIL_USERNAME = 'datshiro@gmail.com'
MAIL_PASSWORD = 'cdifzydebbuycxvy'
